### ISSUE TITLE
GeoMapFish 2.1 - Mapgears

### ISSUE THREAD

**Issue by adube** [camptocamp/c2cgeoportal#2089]
A ticket that tracks the tasks assigned to Mapgears as part of the second phase of development of MapFish 2.0.

 * [x] https://github.com/camptocamp/c2cgeoportal/issues/2040 - Low level editing tools
 * [x] https://github.com/camptocamp/c2cgeoportal/issues/1658 - Measures and redlining
 * [x] https://github.com/camptocamp/c2cgeoportal/issues/2072 - User messages
  * [x] https://github.com/camptocamp/ngeo/issues/921 - Geolocation Failure message
  * [x] https://github.com/camptocamp/ngeo/issues/997 - Login messages uniformity
