### ISSUE TITLE
GeoMapFish - Mapgears (Summer)

### ISSUE THREAD

**Issue by adube** [camptocamp/c2cgeoportal#2267]
A ticket that tracks the tasks assigned to Mapgears as part of the phase to be accomplished during summer.
- [x] https://github.com/camptocamp/c2cgeoportal/issues/1768 - Open a window
- [x] https://github.com/camptocamp/c2cgeoportal/issues/2012 - Background selector
- [x] https://github.com/camptocamp/c2cgeoportal/issues/1769 - Disclaimer
- [x] https://github.com/camptocamp/c2cgeoportal/issues/1770 - Modal Disclaimer
- [x] https://github.com/camptocamp/ngeo/issues/1178 - Draw feature improvements
- [ ] https://github.com/camptocamp/ngeo/issues/1035 Grab on mouse hover (Nice to have)

Related to editing:
- [x] https://github.com/camptocamp/ngeo/issues/1368 - XSD parser
- [ ] https://github.com/camptocamp/c2cgeoportal/issues/1662 - Editing
- [x] https://github.com/camptocamp/ngeo/issues/1452 - Move date picker from GMF to NGEO
